spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: Insa5_SpringB_final_3
    url: jdbc:oracle:thin:@project-db-stu3.smhrd.com:1524:xe
    password: aischool3
    # create database basic

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  websocket:
    enabled: true

server:
  port: '8084'


